### ISSUE TITLE
Teams Bot App with SSO on K8S Experiences Multiple Responses with HPA Scaling Beyond Two Pods

### ISSUE THREAD

**Issue by wiedu-gcws28** [OfficeDev/TeamsFx-Samples#1266]
Hi,

We have developed a bot App by referencing the example of the bot app with SSO Enabled from the teams toolkit sample and deployed it to our on-premise K8S, making it publicly accessible at the service endpoint (https://testdomain.com/service/api/messages). The manifest for this teams bot app has also been uploaded to our organization's apps.

[Teams toolkit SSO Bot Sample](https://i.stack.imgur.com/ElwUF.jpg)

At the same time, we have also created an Azure Bot app resource in Azure and set the message endpoint to point to our service endpoint on K8s

[Azure Bot app message endpoint](https://i.stack.imgur.com/Frm8R.jpg)

Currently, we have encountered an issue where if the HPA on K8s is set with more than two Pods, there is a situation where multiple responses are returned for a single input

[multiple responses are returned for a single input](https://i.stack.imgur.com/pfhfM.jpg)

[HPA Settings in deployment yaml file](https://i.stack.imgur.com/Wu8rv.jpg)

When the HPA is set with only one Pod, it operates normally .

Is there a best practice for HPA settings(we need more than two pods) when deploying with the bot framework (to my knowledge, the teams toolkit bot is based on the bot framework) to avoid this issue?

**Comment by hund030** [comment]
Hi @wiedu-gcws28 
I didn't reproduce your issue. I tried migrating my bot in k8s to horizontal autoscaling and it works fine even there are multiple pods.
There are two pods but only one pod get the request.
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/26134943/87543ffa-c843-4e5f-a4eb-0756e880b425)
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/26134943/28f215f0-2c6c-4a8a-aa57-17251da15415)
And I exactly receive only one response.
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/26134943/c2d0daff-59ee-49bb-af37-2d72f1331231)

I guess there may be an issue in your deployment yaml file rather than in the bot framework. Could you provide more information? The complete yaml file may help.

Here is my deployment yaml file for your reference: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-bot
spec:
  selector:
    matchLabels:
      app: sso-bot
  template:
    metadata:
      labels:
        app: sso-bot
    spec:
      containers:
        - name: sso-bot
          image: <image>
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dev-secrets
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sso-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sso-bot
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: sso-bot
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: sso-bot
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-bot-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <host>
    secretName: tls-secret
  rules:
    - host: <host>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sso-bot
                port:
                  number: 80
```
